apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: jonatasbaldin-spotify
  namespace: openfaas-fn
spec:
  encryptedData:
    spotify_id: AgA0T0cgX3+6oax7poq8z9eGvPHSWEtGwnT4srxV79bXENm2/XSk9Ky0D1jD54h5hhPFsEnfKGj1hLmLBP23lH8ioYdT/KUPpjCIIMILS2Uf1l/FuGQrdk3UfVDTnHDL7TY1+23trxWzq+8u6vs1+K2PBIO7Le3aWgqXWkAxT+mFLk72dzeVt2pRP/lpngy5AHDcNlU6e9A8aA4TEDYzzkocwRvc9lfBbIqzOgbpZ+3IkZxPnz53WymlCgHSStKHbPzGUXvLiYmRuiTg0f6/g7KczvzyDI9v8l776uzSGcKTfmD6rHTfop+YAHHdQ3jaT8gcNo8/+PW9G89s29D1wOBMVvs8/O0e6rAwi66C2eXKFaRSwvCwzNPQUwtUfXxGldZ7II5W+9XERNAXsQ0UXm3Uoh9VR9s2dNA7xKopK1SSbxrHbetvwwo7nKEaLIe0oBsWTpvaLc2LfenkgYo2d9WZ+gbPpQ469Zk4ZjrQZMMAW0i+vjuxf+e4ZQ9aMGyj3fjWMYv7nzJUycdJp+ufj0kt6/Rr6I7KCz+EJ3P/Lhh1GHDGA3R5uUJzCMLNAUHt3aP51oqGW0N4ZtFpMCpzer32HuyHQRtiCxrf7WwMZqOFqghllpTycjdLTMSyLPRbpqirRVmtJWHuW6xP071eht5qndBAhk73XE+mLwICW0MtmTV92sSKjIg1KBcuNKgkoQfVcJw6vs4Cs3+rNTQSYghkzFn/Q4jmAWC9VxPeXx6JhA==
    spotify_secret: AgAHygADV6Ykd3zAdImFuyaxhmMH1mtrgU7Vr4yYNl1goLD4De7WW0BZxjl4CWN0pgRHxluph5BdUXDIcHg6PFlEzhUDx+3UGfVDOwyXRnO8n/ISV7spZYV4mJXduPP7he8iM5PvFMlw4A2H9oUZxMepbVkzBOFzu8Zs22busPI3k++XEPjkb3phtyZbFkpXL3f1paGB0fvHczZo7/Fp6kwknqtWvfoSKOrW8cPIR44q2i3ARCJaw1T/ayRh0gnvkfo18FGTN/W9tFg828XCGJrgGiaeXk9yW5+vQBG6XovKcm6mmOOAe78BW4Z+M2qN/xXFYNjO9W4OPJ75pjaorFp1yUYgnpeijIDu5teNAIPRDeu9g3eZB62qMboF21GWJxiWk4clzMGeWw2Kld70eSRQmhX5Kn+R1fGLYZZu3j4hCbRH0jZcYTeBwEes/zmMalBUvGOqYM+ZKGukxXhEFUfF3bwMh1qRC+QKMnc9QLG3rRoKzt01fqafyQ+373qci0gbUdSzU1YLmn459Q3dIr8PZlO9faVDbdrwNFfALyuf4nZb/yGgdBMLCy8ZovGGE8MPxdA9mAI1Adhie7VbeVx3P8CMcwv5g9WFOnfd/hdYYCCCwFCmL6ZzVX6nfpDLhvbsg0W1sY4pyxVGfO9kXT/pnXcx4zAyk92MKVANTkh7SvZhWqqgSz7B4ikKZSr3Q1vb/D6Xu8DHNFXDtLbLB8kw8TEreDhC8Kpy8nUwOWrAtA==
  template:
    metadata:
      creationTimestamp: null
      name: jonatasbaldin-spotify
      namespace: openfaas-fn
status: {}

