version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:31112
functions:
  brunchies:
    lang: golang-middleware
    handler: ./brunchies
    image: jonatasbaldin/brunchies:latest
    secrets:
      - spotify